version: '2'

services:

  wordpress:
    image: wordpress:4.7.2-php7.1-fpm-alpine
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7.17 
    environment:
      MYSQL_ROOT_PASSWORD: example

  nginx:
    image: nginx:1.10.3-alpine
    ports:
      - "8080:80"
    volumes_from:
      - wordpress:ro
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

