version: '2'

services:

  wordpress:
    image: wordpress:4.7.2-php7.1-fpm-alpine
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wp-content:/var/www/html/wp-content

  mysql:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: wpdb
    volumes:
      - ./mysql-data:/var/lib/mysql

  nginx:
    image: nginx:1.10.3-alpine
    ports:
      - "8080:80"
    volumes_from:
      - wordpress:ro
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
